"""records

Revision ID: c6c44a99c6a2
Revises: 59592c747a42
Create Date: 2025-02-19 09:46:15.351577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c6c44a99c6a2'
down_revision: Union[str, None] = '59592c747a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
                    sa.Column(
                        'token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('data', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('campaign_id', sa.Integer(), nullable=False),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['campaign_id'], ['campaign.id'], ),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_record_id'), 'record', ['id'], unique=False)
    op.drop_index('ix_casereport_id', table_name='casereport')
    op.drop_table('casereport')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casereport',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('campaign_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('company_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('token', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['campaign_id'], ['campaign.id'], name='casereport_campaign_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['company.id'], name='casereport_company_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='casereport_pkey')
                    )
    op.create_index('ix_casereport_id', 'casereport', ['id'], unique=False)
    op.drop_index(op.f('ix_record_id'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
