"""actions

Revision ID: 851959eff484
Revises: c6c44a99c6a2
Create Date: 2025-03-10 08:48:16.334803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '851959eff484'
down_revision: Union[str, None] = 'c6c44a99c6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('company', sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'actions')
    op.drop_column('campaign', 'actions')
    # ### end Alembic commands ###
