"""custom_actions

Revision ID: c0ea045260f9
Revises: b49fa97976c5
Create Date: 2025-04-14 10:04:48.651933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c0ea045260f9'
down_revision: Union[str, None] = 'b49fa97976c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companyaction',
                    sa.Column(
                        'group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('labels', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_companyaction_id'),
                    'companyaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companyaction_id'), table_name='companyaction')
    op.drop_table('companyaction')
    # ### end Alembic commands ###
