"""workplaces

Revision ID: 39d288218439
Revises: 702ae20064c9
Create Date: 2025-12-10 08:35:44.467557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39d288218439'
down_revision: Union[str, None] = '702ae20064c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workplace',
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('lat', sa.Float(), nullable=True),
                    sa.Column('lon', sa.Float(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('campaign_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['campaign_id'], ['campaign.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_workplace_id'), 'workplace', ['id'], unique=False)
    # ### end Alembic commands ###
    # Migrate existing workplace data from campaigns table
    op.execute("""
        INSERT INTO workplace (name, address, lat, lon, campaign_id)
        SELECT name,
               address,
               lat,
               lon,
               id AS campaign_id
        FROM campaign
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workplace_id'), table_name='workplace')
    op.drop_table('workplace')
    # ### end Alembic commands ###
