"""record_timestamps

Revision ID: b49fa97976c5
Revises: 47647b5e1866
Create Date: 2025-03-12 10:43:49.156999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49fa97976c5'
down_revision: Union[str, None] = '47647b5e1866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('record', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'updated_at')
    op.drop_column('record', 'created_at')
    # ### end Alembic commands ###
