"""slug

Revision ID: 9fd5303099d7
Revises: de4dff0b724d
Create Date: 2025-02-17 14:13:25.430611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fd5303099d7'
down_revision: Union[str, None] = 'de4dff0b724d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column(
        'slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'slug')
    # ### end Alembic commands ###
