"""contact-info

Revision ID: 702ae20064c9
Revises: c0ea045260f9
Create Date: 2025-08-26 14:42:01.046962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '702ae20064c9'
down_revision: Union[str, None] = 'c0ea045260f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('contact_email',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('campaign', sa.Column('contact_name',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('campaign', sa.Column(
        'info_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('contact_email',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('contact_name',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column(
        'info_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'info_url')
    op.drop_column('company', 'contact_name')
    op.drop_column('company', 'contact_email')
    op.drop_column('campaign', 'info_url')
    op.drop_column('campaign', 'contact_name')
    op.drop_column('campaign', 'contact_email')
    # ### end Alembic commands ###
