"""

Revision ID: 9fad38829320
Revises: 012b4bcf0fb6
Create Date: 2026-06-22 14:27:23.026830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fad38829320'
down_revision: Union[str, None] = '012b4bcf0fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('with_professional_questions', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'with_professional_questions')
    # ### end Alembic commands ###
