"""

Revision ID: ee8c85f74804
Revises: 495ff1b10270
Create Date: 2026-03-30 18:08:33.417106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ee8c85f74804'
down_revision: Union[str, None] = '495ff1b10270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('response_id', sa.Integer(), nullable=True))
    op.alter_column('record', 'email_hash',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'email_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('record', 'response_id')
    # ### end Alembic commands ###
