"""add_can_be_cited_field_in_company

Revision ID: 1f9348962b84
Revises: a43b487999e9
Create Date: 2026-03-03 10:43:02.359319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9348962b84'
down_revision: Union[str, None] = 'a43b487999e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('can_be_cited', sa.Boolean(), nullable=False, server_default=sa.text("true")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'can_be_cited')
    # ### end Alembic commands ###
