"""open_workplaces

Revision ID: b7ea95a1860b
Revises: 39d288218439
Create Date: 2026-01-05 10:54:18.218798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ea95a1860b'
down_revision: Union[str, None] = '39d288218439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column(
        'open_workplaces', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('campaign', 'lat')
    op.drop_column('campaign', 'address')
    op.drop_column('campaign', 'lon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('lon', sa.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=True))
    op.add_column('campaign', sa.Column(
        'address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaign', sa.Column('lat', sa.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=True))
    op.drop_column('campaign', 'open_workplaces')
    # ### end Alembic commands ###
