"""campaign-nb-employees

Revision ID: a43b487999e9
Revises: 3fe6060330c4
Create Date: 2026-01-22 13:11:04.060440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43b487999e9'
down_revision: Union[str, None] = '3fe6060330c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column(
        'nb_employees', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'nb_employees')
    # ### end Alembic commands ###
