"""

Revision ID: 350291a35af3
Revises: ee8c85f74804
Create Date: 2026-03-30 18:17:15.914950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350291a35af3'
down_revision: Union[str, None] = 'ee8c85f74804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('response_id_in_campaign', sa.Integer(), nullable=True))
    op.drop_column('record', 'response_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('record', 'response_id_in_campaign')
    # ### end Alembic commands ###
